name: "CI/CD Pipeline urushalal FE"

on:
  push:
    branches:
      - development
      - nearlive
      - main


jobs:
  deploy-development:
    name: "Build urushalal FE development "
    if: github.ref_name == 'development'
    uses: ./.github/workflows/template.yml
    with:
      deployment_name: urushalal
      # vault_path: 'dev/data/lomiles-dashboard-customer-v2'
      docker_tags: 'ocistok/urushalal:development' 
      deploy_server: 'https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjMTc1MGY4MDA0ZmI5NGYyYzk2NGY3MTg0OGY4OWU4YzQiLCJpZCI6IjEyNjczNzM1NjcxODg3NDExNSJ9.fJE2WP1JnzupRLM6rEbTzoN6YIuoV1ov6NR3t8AEFr6HvEjezxuRzVk6UQD8jOKYNkDDvXg-ywfi3zDMx6EwP10kKXnbhkTPOlIc1K16b1kXt4v9IRH9BA9IShPC_xro6iDbonKloi-0MabRC6pe-gQn79eKhkHwN6pG_fv8PY0'
      gateway: 'https://gateway-dev.urushalal.id'
    secrets:
      # ROLEID: ${{ secrets.ROLEID }}
      # SECRETID: ${{ secrets.SECRETID }}
      WEBHOOK_DINGTALK: ${{ secrets.WEBHOOK_DINGTALK }}

  deploy-production:
    name: "Build urushalal FE production "
    if: github.ref_name == 'main'
    uses: ./.github/workflows/template.yml
    with:
      deployment_name: urushalal
      docker_tags: 'ocistok/urushalal:production' 
      gateway: 'https://gateway.urushalal.id'      
      deploy_server: 'https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjMTc1MGY4MDA0ZmI5NGYyYzk2NGY3MTg0OGY4OWU4YzQiLCJpZCI6IjEyNzQ1NjczODEzODkyMjUwMSJ9.XClFXXINfOmana39WOvk8YS2X_Ni-laYqIFr7V_6RbSgVCecnSdkOdZVKK1XEXs9SgsfoqBJblHmTR2Dx-xpAVifTXcBep-GdMHa20NaBNfqbZ9knKO5viDp_cCC2IsH_tQLOihecgYu1sBXeSlFwhMEi2_ICGjYge1NNEyE0qg'
    secrets:
      # ROLEID: ${{ secrets.ROLEID }}
      # SECRETID: ${{ secrets.SECRETID }}
      WEBHOOK_DINGTALK: ${{ secrets.WEBHOOK_DINGTALK }}

  deploy-staging:
    name: "Build urushalal FE staging "
    if: github.ref_name == 'nearlive'
    uses: ./.github/workflows/template.yml
    with:
      deployment_name: urushalal
      docker_tags: 'ocistok/urushalal:staging'
      gateway: 'https://gateway.urushalal.id'        
      deploy_server: 'https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjMTc1MGY4MDA0ZmI5NGYyYzk2NGY3MTg0OGY4OWU4YzQiLCJpZCI6IjEyNzQ1NjczODEzODkyMjUwMSJ9.XClFXXINfOmana39WOvk8YS2X_Ni-laYqIFr7V_6RbSgVCecnSdkOdZVKK1XEXs9SgsfoqBJblHmTR2Dx-xpAVifTXcBep-GdMHa20NaBNfqbZ9knKO5viDp_cCC2IsH_tQLOihecgYu1sBXeSlFwhMEi2_ICGjYge1NNEyE0qg'
    secrets:
      # ROLEID: ${{ secrets.ROLEID }}
      # SECRETID: ${{ secrets.SECRETID }}
      WEBHOOK_DINGTALK: ${{ secrets.WEBHOOK_DINGTALK }}

  deploy-staging:
    name: "Build urushalal FE staging "
    if: github.ref_name == 'nearlive'
    uses: ./.github/workflows/template.yml
    with:
      deployment_name: urushalal
      docker_tags: 'ocistok/urushalal:staging' 
      deploy_server: 'https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjMTc1MGY4MDA0ZmI5NGYyYzk2NGY3MTg0OGY4OWU4YzQiLCJpZCI6IjEyNjczNzM1NjcxODg3NDExNSJ9.fJE2WP1JnzupRLM6rEbTzoN6YIuoV1ov6NR3t8AEFr6HvEjezxuRzVk6UQD8jOKYNkDDvXg-ywfi3zDMx6EwP10kKXnbhkTPOlIc1K16b1kXt4v9IRH9BA9IShPC_xro6iDbonKloi-0MabRC6pe-gQn79eKhkHwN6pG_fv8PY0'
    secrets:
      # ROLEID: ${{ secrets.ROLEID }}
      # SECRETID: ${{ secrets.SECRETID }}
      WEBHOOK_DINGTALK: ${{ secrets.WEBHOOK_DINGTALK }}